language: node_js
node_js:
- '0.10'
deploy:
  api_key:
    secure: E10N0cHpENO9HWAzTUDASAd5UonIyqZJR48loFH+hgBrMZ+bwy75IhhgOtO3J8ArzN9NncN3ozhjvKKplfk+ieSuiPUAux0NYonhv+WC059HrGAumySXy/tpPYB6x/nKt/LHaGL/jc/drqviyB044vQifUlNrq6BA7/h3+lHyqc=
  email: anthony@reli.sh
  provider: npm